services:
  node-exporter:
    image: prometheuscommunity/json-exporter:latest
    container_name: nerdqaxe-exporter_1
    user: '1000:1000'
    ports:
      - '7979:7979'
    pid: host
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/config.yml:/config.yml