services:
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter_server_1
    user: '1000:1000'
    ports:
      - '9100:9100'
    pid: host
    restart: unless-stopped