manifestVersion: 1
id: valdobruheim-umbrel-prometheus
name: Prometheus
version: 1.1.0
category: system
icon: ./icon-prometheus.png
port: 9090
path: ""
defaultUsername: ""
defaultPassword: ""
description: "Prometheus metrics collection and storage engine."
repository: "https://github.com/valdobruheim/umbrel-community-app-store/valdobruheim-umbrel-prometheus"
