manifestVersion: 1
id: valdobruheim-umbrel-prometheus
name: Prometheus
version: 3.8.0
category: monitoring
icon: https://github.com/valdobruheim/umbrel-community-app-store/blob/main/galery/prometheus-logo.svg?raw=true
port: 9090
description: >-
  Prometheus metrics collection and storage engine.

  For more information about Prometheus follow the link: https://prometheus.io
developer: The Linux Foundation
website: https://prometheus.io
submitter: Valdo Bruheim
submission: https://github.com/valdobruheim/umbrel-community-app-store
repo: https://github.com/valdobruheim/umbrel-community-app-store/tree/main/valdobruheim-umbrel-prometheus
support: https://github.com/valdobruheim/umbrel-community-app-store/tree/main/valdobruheim-umbrel-prometheus/issues
gallery: []
releaseNotes: >-
  For more information refer to https://prometheus.io
dependencies: []
path: ""
defaultUsername: ""
defaultPassword: ""