services:
  bch-explorer_server:
    image: getumbrel/btc-rpc-explorer:v3.5.1
    container_name: bch-rpc-explorer_server_1
    user: '1000:1000'
    ports:
      - '3005:3002'
    pid: host
    restart: unless-stopped
    environment:
      - BTCEXP_BITCOIND_HOST=retro-mike-bch-node_node_1 # Ensure this matches your BCH container name
      - BTCEXP_BITCOIND_PORT=9002
      - BTCEXP_BITCOIND_USER=pooluser
      - BTCEXP_BITCOIND_PASS=poolpassword
      - BTCEXP_HOST=0.0.0.0
      - BTCEXP_NO_INCENTIVES=true