id: prometheus
name: Prometheus
version: 1.1.0
category: system
icon: ./icon-prometheus.png
port: 9090

services:
  - prometheus

description: "Prometheus metrics collection and storage engine."
repository: "https://github.com/your/prometheus-app"
